# Generated by Django 2.0.7 on 2020-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('CIV', 'CIV'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('BS', 'BS'), ('MBA', 'MBA')], max_length=100)),
                ('dept_id', models.IntegerField()),
                ('AICTE_id', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=50)),
                ('mobile_No', models.IntegerField()),
                ('email_id', models.EmailField(max_length=250)),
                ('aadhar_No', models.CharField(max_length=50)),
                ('pan_No', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[('Doctorate', 'Doctorate'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=50)),
                ('ug_percentage', models.IntegerField()),
                ('ug_award_year', models.IntegerField()),
                ('pg', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('pg_percentage', models.IntegerField(blank=True)),
                ('pg_award_year', models.IntegerField(blank=True)),
                ('phd_award_year', models.IntegerField()),
                ('ratified', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('No_of_papers_published', models.IntegerField()),
                ('No_of_books_published', models.IntegerField()),
                ('No_of_paytents', models.IntegerField()),
                ('No_of_rnd_projects', models.IntegerField()),
                ('No_of_phd_guides', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_relieving', models.DateField()),
            ],
        ),
    ]
