# Generated by Django 2.0.7 on 2020-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_relieving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pg_award_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pg_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
