from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from .views import (
		FacultyListView,
		FacultyDetailView,
		cse_view,
		it_view,
		ece_view,
		eee_view,
		civ_view,
		mec_view,
		bs_view,
		mba_view,
		home,
		doctorates_view,
		doctorates_eee,
		doctorates_ece,
		doctorates_cse,
		doctorates_it,
		doctorates_mec,
		doctorates_civ,
		doctorates_bs,
		doctorates_mba,
		professors,
		professors_eee,
		professors_cse,
		professors_ece,
		professors_it,
		professors_mec,
		professors_civ,
		professors_bs,
		professors_mba,
		associate,
		associate_eee,
		associate_cse,
		associate_it,
		associate_ece,
		associate_civ,
		associate_mec,
		associate_bs,
		associate_mba,
		assisstant,
		assisstant_eee,
		assisstant_cse,
		assisstant_it,
		assisstant_ece,
		assisstant_civ,
		assisstant_mec,
		assisstant_bs,
		assisstant_mba,
		ratified,
		ratified_cse,
		ratified_it,
		ratified_ece,
		ratified_eee,
		ratified_civ,
		ratified_mec,
		ratified_bs,
		ratified_mba,

		non_ratified,
		non_ratified_cse,
		non_ratified_it,
		non_ratified_ece,
		non_ratified_eee,
		non_ratified_civ,
		non_ratified_mec,
		non_ratified_bs,
		non_ratified_mba,

		tempraryview,
		navbar
	)

app_name='faculty'
urlpatterns = [
path('navbar/', navbar),
	path('', FacultyListView.as_view(), name='faculty_list'),
	path('<int:id>/', FacultyDetailView.as_view(), name='faculty_detail'),
	path('cse/', cse_view.as_view(), name='cse-faculty'),
	path('it/', it_view.as_view(), name='it-faculty'),
	path('ece/', ece_view.as_view(), name='ece-faculty'),
	path('eee/', eee_view.as_view(), name='eee-faculty'),
	path('civ/', civ_view.as_view(), name='civ-faculty'),
	path('mec/', mec_view.as_view(), name='mec-faculty'),
	path('bs/', bs_view.as_view(), name='bs-faculty'),
	path('mba/', mba_view.as_view(), name='mba-faculty'),
	path('index/', tempraryview.as_view(), name='abc'),

	path('doctorates/', doctorates_view.as_view(), name='doctorates'),
	path('doctorates/eee/', doctorates_eee.as_view(), name='doctorates-eee'),
	path('doctorates/cse/', doctorates_cse.as_view(), name='doctorates-cse'),
	path('doctorates/civ/', doctorates_civ.as_view(), name='doctorates-civ'),
	path('doctorates/mba/', doctorates_mba.as_view(), name='doctorates-mba'),
	path('doctorates/bs/', doctorates_bs.as_view(), name='doctorates-bs'),
	path('doctorates/it/', doctorates_it.as_view(), name='doctorates-it'),
	path('doctorates/mec/', doctorates_mec.as_view(), name='doctorates-mec'),
	path('doctorates/ece/', doctorates_ece.as_view(), name='doctorates-ece'),

	path('professors/', professors.as_view(), name='professors'),
	path('professors/ece/', professors_ece.as_view(), name='professors-ece'),
	path('professors/bs/', professors_bs.as_view(), name='professors-bs'),
	path('professors/mec/', professors_mec.as_view(), name='professors-mec'),
	path('professors/civ/', professors_civ.as_view(), name='professors-civ'),
	path('professors/eee/', professors_eee.as_view(), name='professors-eee'),
	path('professors/it/', professors_it.as_view(), name='professors-it'),
	path('professors/cse/', professors_cse.as_view(), name='professors-cse'),
	path('professors/mba/', professors_mba.as_view(), name='professors-mba'),

	path('associate/', associate.as_view(), name='associate'),
	path('associate/ece/', associate_ece.as_view(), name='associate-ece'),
	path('associate/bs/', associate_bs.as_view(), name='associate-bs'),
	path('associate/mec/', associate_mec.as_view(), name='associate-mec'),
	path('associate/civ/', associate_civ.as_view(), name='associate-civ'),
	path('associate/eee/', associate_eee.as_view(), name='associate-eee'),
	path('associate/it/', associate_it.as_view(), name='associate-it'),
	path('associate/cse/', associate_cse.as_view(), name='associate-cse'),
	path('associate/mba/', associate_mba.as_view(), name='associate-mba'),

	path('assisstant/', assisstant.as_view(), name='assisstant'),
	path('assisstant/ece/', assisstant_ece.as_view(), name='assisstant-ece'),
	path('assisstant/bs/', assisstant_bs.as_view(), name='assisstant-bs'),
	path('assisstant/mec/', assisstant_mec.as_view(), name='assisstant-mec'),
	path('assisstant/civ/', assisstant_civ.as_view(), name='assisstant-civ'),
	path('assisstant/eee/', assisstant_eee.as_view(), name='assisstant-eee'),
	path('assisstant/it/', assisstant_it.as_view(), name='assisstant-it'),
	path('assisstant/cse/', assisstant_cse.as_view(), name='assisstant-cse'),
	path('assisstant/mba/', assisstant_mba.as_view(), name='assisstant-mba'),

	path('ratified/', ratified.as_view(), name='ratified'),
	path('ratified/ece/', ratified_ece.as_view(), name='ratified-ece'),
	path('ratified/bs/', ratified_bs.as_view(), name='ratified-bs'),
	path('ratified/mec/', ratified_mec.as_view(), name='ratified-mec'),
	path('ratified/civ/', ratified_civ.as_view(), name='ratified-civ'),
	path('ratified/eee/', ratified_eee.as_view(), name='ratified-eee'),
	path('ratified/it/', ratified_it.as_view(), name='ratified-it'),
	path('ratified/cse/', ratified_cse.as_view(), name='ratified-cse'),
	path('ratified/mba/', ratified_mba.as_view(), name='ratified-mba'),

	# path('non-ratified/', non_ratified.as_view(), name='non-ratified'),
	# path('non-ratified/ece/', non_ratified_ece.as_view(), name='non-ratified-ece'),
	# path('non-ratified/bs/', non_ratified_bs.as_view(), name='non-ratified-bs'),
	# path('non-ratified/mec/', non_ratified_mec.as_view(), name='non-ratified-mec'),
	# path('non-ratified/civ/', non_ratified_civ.as_view(), name='non-ratified-civ'),
	# path('non-ratified/eee/', non_ratified_eee.as_view(), name='non-ratified-eee'),
	# path('non-ratified/it/', non_ratified_it.as_view(), name='non-ratified-it'),
	# path('non-ratified/cse/', non_ratified_cse.as_view(), name='non-ratified-cse'),
	# path('non-ratified/mba/', non_ratified_mba.as_view(), name='non-ratified-mba'),
	

	path('home/', home, name='home')
	
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)